### ISSUE TITLE
Maximum Stack Size Exceeded

### ISSUE THREAD

**Issue by Diniden** [mobxjs/mobx#236]
I made a simple application that has a store structured something like this:
```
{
  tableData: []
  ,sortColumn: 0
  ,headerTypes: [Number, Date, String, String, String]
}
```
All of that is observable. I then made a computed view of the table data:

```
@computed get sortedData() {
    return this.tableData.sort(this.getSortFn(this.sortType, this.sortColumn));
  }
```

I then fill the tableData with ~10000 items that contains data like:

[0, new Date(), "foo", "foo", "foo"]

and I render it out via:

```
import React, { Component, PropTypes } from 'react';
import {observer} from "mobs-react";
import Row from './Flexbox/Row.jsx';
import Col from './Flexbox/Col.jsx';
import Box from './Flexbox/Box.jsx';
import DemoListItem from './DemoListItem.jsx';
import store from '../Store/DemoTableStore.jsx';

observer
class DemoTableListItemsView extends Component {
  render() {
    let table = [];
    const { tableData } = this.props;

    for(var i=0, end=tableData.length; i<end; ++i) {
      table.push(<DemoListItem key={tableData[i][0]} data={tableData[i]}/>);
    }

    return <div>{table}</div>;
  }
}

@observer
class DemoTable extends Component {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div style={{ margin: 20, backgroundColor: '#E4E4E4' }}>
        <Row style={{ width: '100%', left: 16, backgroundColor: '#A4A4A4', margin: 0 }}>
          <Col className="col-xs">
            <Box border={0}>
              <p style={{ textAlign: 'center', borderRadius: '0.2em' }}>
                  <span>Number</span>
              </p>
            </Box>
          </Col>
          <Col className="col-xs">
          <Box>
              <p style={{ textAlign: 'center', borderRadius: '0.2em' }}>
                  <span>Date</span>
              </p>
          </Box>
          </Col>
          <Col className="col-xs">
          <Box >
              <p style={{ textAlign: 'center', borderRadius: '0.2em' }}>
                  <span >String</span>
              </p>
          </Box>
          </Col>
          <Col className="col-xs">
          <Box >
              <p style={{ textAlign: 'center', borderRadius: '0.2em' }}>
                  <span >Info1</span>
              </p>
          </Box>
          </Col>
          <Col className="col-xs">
          <Box >
              <p style={{ textAlign: 'center', borderRadius: '0.2em' }}>
                  <span >Info2</span>
              </p>
          </Box>
          </Col>
        </Row>
        {/*Recommended pattern by mobx, rendering a list with a component who's only job is to render the list*/}
        <DemoTableListItemsView tableData={store.sortedData}/>
      </div>
    );
  }
}

export default DemoTable;
```

Trying to change my sort column, I get this spewing out from mobx:

```
[Error] RangeError: Maximum call stack size exceeded.
  quickDiff (bundle.js:39528)
  bindDependencies (bundle.js:38499)
  trackDerivedFunction (bundle.js:38485)
  trackAndCompute (bundle.js:38425)
  onDependenciesReady (bundle.js:38399)
  notifyDependencyReady (bundle.js:38468)
  (anonymous function) (bundle.js:38586:93)
  forEach
  propagateReadiness (bundle.js:38586)
  propagateAtomReady (bundle.js:38314)
  reportReady (bundle.js:38350)
  reportChanged (bundle.js:38335)
  set (bundle.js:39349)
  (anonymous function) (bundle.js:39297)
  sortColumn (bundle.js:147)
  (anonymous function) (bundle.js:203)
  handleMouseUp (bundle.js:15937)
  (anonymous function)
  dispatchEvent
  invokeGuardedCallback (bundle.js:50174)
  executeDispatch (bundle.js:42419)
  executeDispatchesInOrder (bundle.js:42439)
  executeDispatchesAndRelease (bundle.js:41890)
  executeDispatchesAndReleaseTopLevel (bundle.js:41901)
  forEach
  forEachAccumulated (bundle.js:56402)
  processEventQueue (bundle.js:42063)
  runEventQueueInBatch (bundle.js:50201)
  handleTopLevel (bundle.js:50212)
  handleTopLevelImpl (bundle.js:50290)
  perform (bundle.js:55852)
  batchedUpdates (bundle.js:48863)
  batchedUpdates (bundle.js:53572)
  dispatchEvent (bundle.js:50367)
  (anonymous function)
```

I understand 10000 rows is a lot, but why would it only explode on a computed sort? I can keep inserting more elements without any issues. Let me know if I need to be clearer or if more code is needed.

**Comment by mweststrate** [comment]
Just pushed version `2.1.6` which should address this issue. It might be the case that the call stack issue is disappeared but that the operation is slow, just let me know if that is the case.

**Comment by mweststrate** [comment]
@Diniden could you indicate whether this issue has been resolved sufficiently? Thanks!

**Comment by nyura123** [comment]
Hi @mweststrate, thank you for this awesome lib! I had the same issue & your fix worked for me - thanks!

**Comment by Diniden** [comment]
Sorry for taking so long :) Lots to sort through.

I just tested your latest, and the issue went away for me. Thanks! I'll let you know if I encounter it again.

The sort is a little slowish, but it's not from re-triggering renderings, which is all that I care about. I believe most of the slowness is just the browser re-rendering, I haven't had time to profile the actual sort operation on the data alone. I'll let you know if that is an issue in a separate ticket if I get time.

**Comment by timeyr** [comment]
I assume that in this case this means that I have a cyclic dependency among my observers, right?

mobx.js:640 Uncaught RangeError: Maximum call stack size exceeded
@ mobx.js:640findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle
@ mobx.js:647findCycle

**Comment by mweststrate** [comment]
correct. nasty, this is exactly the kind of situation that `findCycle` tries to find and report. Can you try to reproduce this issue in a fiddle or some other place where I can test it? Thanks in advance!

**Comment by timeyr** [comment]
This is a bit ugly, because logically (i.e. when looking at the values of the variables), there will never be a cycle. However programmatically this cannot be detected, I guess:

```
import { extendObservable, autorun } from 'mobx';

Parent = function() {
    extendObservable(this, {
        children: [],
        total0: function() {
            // Sum "value" of children of kind "0"
            return this.children.filter(c => c.kind === 0).map(c => c.value).reduce((a, b) => a+b, 0);
        },
        total1: function() {
            // Sum "value" of children of kind "1"
            return this.children.filter(c => c.kind === 1).map(c => c.value).reduce((a, b) => a+b, 0);
        }
    });
};

Child = function(parent, kind) {
    this.parent = parent;
    extendObservable(this, {
        kind: kind,
        value: function() {
            if (this.kind === 0) {
                return 3;
            } else {
                // Value of child of kind "1" depends on the total value for all children of kind "0"
                return this.parent.total0 * 2;
            }
        }
    });
};

const parent = new Parent();
parent.children.push(new Child(parent, 0));
parent.children.push(new Child(parent, 0));
parent.children.push(new Child(parent, 0));

autorun(() => {
    console.log('total0:', parent.total0, 'total1:', parent.total1);
});

// So far, so good: total0: 9 total1: 0

parent.children[0].kind = 1;

// Uncaught RangeError: Maximum call stack size exceeded
```

**Comment by mweststrate** [comment]
@timeyr thanks for the code! really useful. I just released `2.1.7` where the cycle detection is fixed and the cycle is now reported properly.

But indeed, if cycle reporting is completely disabled in the MobX code, the above snippet terminates correctly. I'm gonna dive a bit deeper to figure out if this is either a situation that should not be reported as cycle, or that should be encoded in a different way.

**Comment by mweststrate** [comment]
@timeyr note that at least the following work around works:

```javascript
	var Parent = function() {
...
			total0: function() {
				// Sum "value" of children of kind "0"
				return this.children.filter(c => c.isKind0).map(c => c.value).reduce((a, b) => a+b, 0);
			},
			total1: function() {
				// Sum "value" of children of kind "1"
				return this.children.filter(c => c.isKind1).map(c => c.value).reduce((a, b) => a+b, 0);
			}
...
	var Child = function(parent, kind) {
		m.extendObservable(this, {
			kind: kind,
			isKind0: true,
			isKind1: false,
...
		});
	};
...
	transaction(() => {
		parent.children[0].kind0 = false;
		parent.children[0].kind1 = true;
	});
```

**Comment by timeyr** [comment]
Hm, the only change is that you introduced a Boolean to implement the filter? It's not obvious why this would allow the cycle detection to work correctly... In any case, thanks a lot for your help, will update to 2.1.7 tonight and do some more tests.

**Comment by mweststrate** [comment]
ah that is quite simple:

`total0` depends initially on the value of `value` of _all_ children initially (they are needed in the map. 
However the `value` of kind 1 children itself depends on the same `total0`. Hence this is seen as a cycle. 

But I think that you are right that in this specific case this is technically a false positive for the cycle detection, I'll investigate whether I can recognize this situation. So thanks for reporting!

**Comment by timeyr** [comment]
I still don't get it: why does it depend on _all_ children? The filter is applied before the map (both in your and in my example) such that `Child.value` should only be called for either kind-0 children or kind-1 children.

**Comment by mweststrate** [comment]
It's due to the moment at which the cycles are detected: Initially, `total0` depends on your third child's value. During the assignment your third child starts to depend on `total0`. Before the dependency is registered it will first check whether adding `total0` to the dependency tree of `value` won't introduce a cycle, which is still the case at that moment, because `total0` is needs to be re-evaluated at which point it would no longer depend on your third child.

So to solve this problem the cycle detection should only be done after _both_ `total0` and `child3.value` have been re-evaluated (swapping execution order won't help because then you would have this problem when going from kind `1` to kind `0`). The nasty thing here is, if the cycle detection is done later, and there is a real cycle in the computations, you will get a stack overflow before the cycle detection kicks in, so I am not sure yet whether this is a solvable scenario yet.

**Comment by timeyr** [comment]
Wow, this is really tricky, but I think I got it now! Thanks for taking the time to explain!

**Comment by huadong** [comment]
Can't detect this cycle reference? 

```ts
class MenuItem {
    id: string;
    type: number;
    label: string;
    link?: string;
    parent?: MenuItem;
    items?: Array<MenuItem>;
    style?: string;
    comment?: string;
    status: number;
}

const menus: Array<MenuItem> = [
    {
        id: 'file',
        type: 0,
        label: 'File',
        status: 0,
        items: [
            {
                id: 'edit',
                type: 0,
                label: 'Edit',
                status: 0,
            },
            {
                id: 'save',
                type: 0,
                label: 'Save',
                status: 0,
            },
        ]
    },
];

function buildMenu(menus: Array<MenuItem>): Array<MenuItem> {
    menus.forEach((menu) => {
        if(menu.items) {
            //set parent
            menu.items.forEach((item) => {
                item.parent = menu;
            });
            buildMenu(menu.items);
        }
    });
    return menus;
}

class Store {
    @observable _menus: Map<string, MenuItem> = new Map();

    @action addMenu(menu: MenuItem): MenuItem {
        this._menus.set(menu.id, menu);

        return this.getMenu(menu.id);
    }
}

//main
let store = new Store();
transaction(() =>{
    buildMenu(menus).forEach((menu) => {
        store.addMenu(menu);
    });
});
```

> Uncaught RangeError: Maximum call stack size exceeded
>     at invariant (mobx.module.js?f3e0:2320)
>     at extendObservableHelper (mobx.module.js?f3e0:1778)
>     at extendObservable (mobx.module.js?f3e0:1768)
>     at Function.object (mobx.module.js?f3e0:1867)
>     at deepEnhancer (mobx.module.js?f3e0:1956)
>     at new ObservableValue (mobx.module.js?f3e0:765)
>     at defineObservableProperty (mobx.module.js?f3e0:1605)
>     at defineObservablePropertyFromDescriptor (mobx.module.js?f3e0:1584)
>     at extendObservableHelper (mobx.module.js?f3e0:1796)
>     at extendObservable (mobx.module.js?f3e0:1768)

**Comment by mweststrate** [comment]
`item.parent = menu` creates a cycle

Op zo 4 feb. 2018 om 16:32 schreef huadong <notifications@github.com>:

**Comment by huadong** [comment]
May I use this kind of object which contains circular reference as an observable object?

**Comment by mweststrate** [comment]
yes circular refs can be used, but best use your class in that case, so that you can mark for example `menuItem.parent` as `@observable.ref` and avoid endless recursion of trying to convert your circular data structures to observables

**Comment by huadong** [comment]
Thanks a lot! 

It have been achieved by adding @observable.ref to menuItem.parent.
The menuItem.parent=<the reference of plain object> after menuItem had been wrapped by MOBX.

Is there any automatable mechanism to update the menuItem.parent to the new observable reference?

**Comment by huadong** [comment]
These are the source codes in my project. I don't know whether it's the right way of using mobx.

```ts
import { observable, action, computed } from 'mobx';

export interface MenuItem {
    id: string;
    type: number;
    label: string;
    link?: string;
    items?: Array<MenuItem>;
    style?: string;
    comment?: string;
    status: number;
}

export class Menu implements MenuItem{
    @observable id: string;
    @observable type: number;
    @observable label: string;
    @observable link?: string;
    @observable.ref _parent?: Menu;
    @observable items?: Array<Menu>;
    @observable style?: string;
    @observable comment?: string;
    @observable status: number;

    constructor(menu?: MenuItem, parent?: Menu) {
        if(menu) {
            Object.assign(this, menu);
        }

        if(menu.items) {
            this.items = [];
            menu.items.forEach((item)=>{
                this.items.push(new Menu(item, this));
            });
        }

        if(parent) {
            this.setParent(parent);
        }
    }

    @action setParent(parent: Menu) {
        this._parent = parent;
    }

    @computed get path(): string {
        let path = this.id;
        let p = this._parent;
        while(p) {
            path = `${p.id}/${path}`;
            p=p._parent;
        }
        return `/${path}`;
    }

    @computed get parent(): Menu {
        return this._parent;
    }

    @action addItem(item: MenuItem) {
        if(this.items == null) {
            this.items = [];
        }
        //to Menu
        this.items.push(new Menu(item, this));
    }

    @action addMenu(menu: Menu) {
        if(this.items == null) {
            this.items = [];
        }
        //set parent
        menu.setParent(this);
        this.items.push(menu);
    }

    @action removeItem(id: string): Menu {
        let item: Menu = null;
        if(this.items) {
            for (let i = 0; i < this.items.length; i++) {
                if(this.items[i].id == id) {
                    //remove also with parent
                    item = this.items.splice(i, 1)[0];
                    item.setParent(null);
                    break;
                }
            }
        }

        return item;
    }

    findItem(id: string): Menu {
        let item: Menu = null;
        if(this.items) {
            for (let i = 0; i < this.items.length; i++) {
                if(this.items[i].id == id) {
                    item = this.items[i];
                    break;
                }
            }
        }
        return item;
    }
}

export default Menu;
```

```ts
export class Store {
    
    @observable _menus: Map<string, Menu> = new Map();

    @action addMenu(menu: Menu): Menu {
        this._menus.set(menu.id, menu);

        return this.getMenu(menu.id);
    }

    @computed get menus(): Array<Menu> {
        let menus: Array<Menu> = [];
        this._menus.forEach((m) => {
            menus.push(m);
        });
        return menus;
    }
}
```
